<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="basicfamily" nsURI="http://www.example.org/basicfamily" nsPrefix="basicfamily">
  <eSubpackages name=" QoS">
    <eClassifiers xsi:type="ecore:EClass" name="QoSCharacteristics" eSuperTypes="#//%20QoS/QoSContext">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInvariant" ordered="false"
          unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
          changeable="false" defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qSub" upperBound="-1"
          eType="#//%20QoS/QoSCharacteristics" eOpposite="#//%20QoS/QoSCharacteristics/qParent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qParent" upperBound="-1"
          eType="#//%20QoS/QoSCharacteristics" eOpposite="#//%20QoS/QoSCharacteristics/qSub"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qTemplate" eType="#//%20QoS/QoSCharacteristics"
          eOpposite="#//%20QoS/QoSCharacteristics/qDerivation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qDerivation" upperBound="-1"
          eType="#//%20QoS/QoSCharacteristics" eOpposite="#//%20QoS/QoSCharacteristics/qTemplate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" eType="#//%20QoS/QoSDimension"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          upperBound="-1" eType="#//%20QoS/QoSParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" upperBound="-1"
          eType="#//%20QoS/QoSContext" eOpposite="#//%20QoS/QoSContext/basedOn"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSContract" eSuperTypes="#//%20QoS/QoSConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requireAccorded" upperBound="-1"
          eType="#//%20QoS/QoSRequired" eOpposite="#//%20QoS/QoSRequired/contract"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="offerAccorded" upperBound="-1"
          eType="#//%20QoS/QoSOffered" eOpposite="#//%20QoS/QoSOffered/contract"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSTransition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//%20QoS/QoSLevel"
          eOpposite="#//%20QoS/QoSLevel/from"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//%20QoS/QoSLevel"
          eOpposite="#//%20QoS/QoSLevel/to"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSCompoundConstraint" eSuperTypes="#//%20QoS/QoSConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
          eType="#//%20QoS/QoSConstraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="level" eType="#//%20QoS/QoSCompoundLevel"
          eOpposite="#//%20QoS/QoSCompoundLevel/allowedSpace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="evaluate" upperBound="-1"
          eType="#//%20QoS/QoSValue"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualification" eType="#//%20QoS/QualificationKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="logicalOperator" eType="#//%20QoS/LogicalOperators"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//%20QoS/QoSConstraint"
          eOpposite="#//%20QoS/QoSConstraint/previous"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//%20QoS/QoSConstraint"
          eOpposite="#//%20QoS/QoSConstraint/next"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//%20QoS/QoSContext"
          eOpposite="#//%20QoS/QoSContext/support"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentLevel" upperBound="-1"
          eType="#//%20QoS/QoSLevel" eOpposite="#//%20QoS/QoSLevel/allowedSpace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSDimentionSlot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedValue" eType="#//%20QoS/QoSValue"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSOffered" eSuperTypes="#//%20QoS/QoSConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contract" upperBound="-1"
          eType="#//%20QoS/QoSContract" eOpposite="#//%20QoS/QoSContract/offerAccorded"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qRequired" upperBound="-1"
          eType="#//%20QoS/QoSRequired" eOpposite="#//%20QoS/QoSRequired/qOffered"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSRequired" eSuperTypes="#//%20QoS/QoSConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contract" upperBound="-1"
          eType="#//%20QoS/QoSContract" eOpposite="#//%20QoS/QoSContract/requireAccorded"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qOffered" upperBound="-1"
          eType="#//%20QoS/QoSOffered" eOpposite="#//%20QoS/QoSOffered/qRequired"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSParameter" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eClassifiers xsi:type="ecore:EClass" name="QoSValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownerValue" lowerBound="1"
          upperBound="-1" eType="#//%20QoS/QoSDimentionSlot" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSDimension">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//%20QoS/DirectionKind"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="statisticalQualifier"
          eType="#//%20QoS/QoSStatisticalAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Type" eType="#//%20QoS/QoSCharacteristics"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="evaluate" lowerBound="1"
          upperBound="-1" eType="#//%20QoS/QoSDimentionSlot" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSLevel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allowedSpace" upperBound="-1"
          eType="#//%20QoS/QoSConstraint" eOpposite="#//%20QoS/QoSConstraint/currentLevel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" upperBound="-1"
          eType="#//%20QoS/QoSTransition" eOpposite="#//%20QoS/QoSTransition/destination"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" upperBound="-1" eType="#//%20QoS/QoSTransition"
          eOpposite="#//%20QoS/QoSTransition/source"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSContext">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOoSObeservation" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="oppositeAssociation"
          upperBound="-1" eType="#//%20QoS/QoSContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="support" upperBound="-1"
          eType="#//%20QoS/QoSConstraint" eOpposite="#//%20QoS/QoSConstraint/context"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="basedOn" upperBound="-1"
          eType="#//%20QoS/QoSCharacteristics" eOpposite="#//%20QoS/QoSCharacteristics/context"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSCategory">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenced" upperBound="-1"
          eType="#//%20QoS/QoSCategory"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="own" eType="#//%20QoS/QoSCategory"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//%20QoS/QoSCharacteristics"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QoSCompoundLevel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allowedSpace" eType="#//%20QoS/QoSCompoundConstraint"
          eOpposite="#//%20QoS/QoSCompoundConstraint/level"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="groupOfLevel" upperBound="-1"
          eType="#//%20QoS/QoSLevel" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DirectionKind">
      <eLiterals name="increasing"/>
      <eLiterals name="decreasing" value="1"/>
      <eLiterals name="undefined" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="QoSStatisticalAttribute">
      <eLiterals name="maximum value"/>
      <eLiterals name="minimum value" value="1"/>
      <eLiterals name="range" value="2"/>
      <eLiterals name="mean" value="3"/>
      <eLiterals name="variance" value="4" literal="variance"/>
      <eLiterals name="standard deviation" value="5"/>
      <eLiterals name="percentile" value="6" literal="percentile"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="QualificationKind">
      <eLiterals name="Guarantee"/>
      <eLiterals name="Best-Effort" value="1"/>
      <eLiterals name="ThresholdBest-Effort" value="2"/>
      <eLiterals name="Compulsory-Best-Effort" value="3"/>
      <eLiterals name="none" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="LogicalOperators">
      <eLiterals name="and"/>
      <eLiterals name="or" value="1"/>
      <eLiterals name="none" value="2"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
