<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uafMetadata" nsURI="http://www.example.org/uafMetadata" nsPrefix="uafMetadata">
  <eSubpackages name="Taxonomy">
    <eClassifiers xsi:type="ecore:EClass" name="Metadata" eSuperTypes="#//Taxonomy/MeasurableElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaDataScheme" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dublinCoreTag" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArchitectureMetad" eSuperTypes="#//Taxonomy/Metadata">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" lowerBound="1"
          upperBound="-1" eType="#//Taxonomy/Description" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Description"/>
    <eClassifiers xsi:type="ecore:EClass" name="MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionScenarioGeneralization"
        eSuperTypes="#//Taxonomy/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="InteractionScenario">
      <eStructuralFeatures xsi:type="ecore:EReference" name="generalInterationScenario"
          lowerBound="1" upperBound="-1" eType="#//Taxonomy/InteractionScenarioGeneralization"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specificInteractionScenario"
          lowerBound="1" upperBound="-1" eType="#//Taxonomy/InteractionScenarioGeneralization"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessGeneralization" eSuperTypes="#//Taxonomy/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Proces">
      <eStructuralFeatures xsi:type="ecore:EReference" name="specificProcess" lowerBound="1"
          upperBound="-1" eType="#//Taxonomy/ProcessGeneralization" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="generalProcess" lowerBound="1"
          upperBound="-1" eType="#//Taxonomy/ProcessGeneralization" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertySetGeneralization" eSuperTypes="#//Taxonomy/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="PropertySet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="generalPropertySet" lowerBound="1"
          upperBound="-1" eType="#//Taxonomy/PropertySetGeneralization" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specificPropertySet"
          lowerBound="1" upperBound="-1" eType="#//Taxonomy/PropertySetGeneralization"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CapabilityGeneralization" eSuperTypes="#//Taxonomy/PropertySetGeneralization"/>
    <eClassifiers xsi:type="ecore:EClass" name="StateDescriptionGeneralization" eSuperTypes="#//Taxonomy/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="StateDescription">
      <eStructuralFeatures xsi:type="ecore:EReference" name="generalStateDescription"
          lowerBound="1" upperBound="-1" eType="#//Taxonomy/StateDescriptionGeneralization"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specificStateDescription"
          lowerBound="1" upperBound="-1" eType="#//Taxonomy/StateDescriptionGeneralization"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Structure">
    <eClassifiers xsi:type="ecore:EClass" name="MeasurableElemen"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnvironmentProperty" eSuperTypes="#//Structure/MeasurableElemen">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Structure/Condition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Condition"/>
    <eClassifiers xsi:type="ecore:EClass" name="Environment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditionProperty" upperBound="-1"
          eType="#//Structure/EnvironmentProperty" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Connectivity">
    <eClassifiers xsi:type="ecore:EClass" name="Exchange" abstract="true" eSuperTypes="#//Connectivity/MeasurableElement #//Connectivity/SubjectOfSecurityConstrain"/>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceMessage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizes" upperBound="-1"
          eType="#//Connectivity/Exchange" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubjectOfSecurityConstrain"/>
    <eClassifiers xsi:type="ecore:EClass" name="MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalExchange" eSuperTypes="#//Connectivity/Exchange"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceExchange" eSuperTypes="#//Connectivity/Exchange"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExchangeItem" abstract="true" eSuperTypes="#//Connectivity/BPMNMessage"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceExchangeItem" eSuperTypes="#//Connectivity/ExchangeItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalExchangeItem" eSuperTypes="#//Connectivity/ExchangeItem"/>
    <eClassifiers xsi:type="ecore:EEnum" name="OperationalExchangeItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="NewEClass10"/>
    <eClassifiers xsi:type="ecore:EEnum" name="BPMN2Metamodel::BPMNMessage"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NewDataType3" instanceTypeName="newDataType3"/>
    <eClassifiers xsi:type="ecore:EClass" name="BPMNMessage"/>
    <eClassifiers xsi:type="ecore:EClass" name="PropertySet"/>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" abstract="true" eSuperTypes="#//Connectivity/PropertySet"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalExchangeItem" eSuperTypes="#//Connectivity/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceExchangeItem" eSuperTypes="#//Connectivity/Resource"/>
  </eSubpackages>
  <eSubpackages name="Processes">
    <eClassifiers xsi:type="ecore:EClass" name="MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityPerformableUnderCondition"
        eSuperTypes="#//Processes/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ActualCondition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditio" lowerBound="1"
          upperBound="-1" eType="#//Processes/ActivityPerformableUnderCondition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Process">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          upperBound="-1" eType="#//Processes/ActivityPerformableUnderCondition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IsCapableToPerform" eSuperTypes="#//Processes/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalActivity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="performedActivity" lowerBound="1"
          upperBound="-1" eType="#//Processes/IsCapableToPerform" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceFunction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="serviceFunction" lowerBound="1"
          upperBound="-1" eType="#//Processes/IsCapableToPerform" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Function">
      <eStructuralFeatures xsi:type="ecore:EReference" name="performedFunction" lowerBound="1"
          upperBound="-1" eType="#//Processes/IsCapableToPerform" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalAgent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="performingOperationalPerformer"
          lowerBound="1" upperBound="-1" eType="#//Processes/IsCapableToPerform" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceSpecification">
      <eStructuralFeatures xsi:type="ecore:EReference" name="serviceSpecification"
          lowerBound="1" upperBound="-1" eType="#//Processes/IsCapableToPerform" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourcePerformer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="performingResource" lowerBound="1"
          upperBound="-1" eType="#//Processes/IsCapableToPerform" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PerformsInContext" eSuperTypes="#//Processes/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalRole">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operationalRole" lowerBound="1"
          upperBound="-1" eType="#//Processes/PerformsInContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalActivityAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          upperBound="-1" eType="#//Processes/PerformsInContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
          upperBound="-1" eType="#//Processes/PerformsInContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceRole">
      <eStructuralFeatures xsi:type="ecore:EReference" name="usage" lowerBound="1"
          upperBound="-1" eType="#//Processes/PerformsInContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceSpecificationRole">
      <eStructuralFeatures xsi:type="ecore:EReference" name="serviceRole" lowerBound="1"
          upperBound="-1" eType="#//Processes/PerformsInContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceFunctionAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="serviceAction" lowerBound="1"
          upperBound="-1" eType="#//Processes/PerformsInContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//Processes/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceFunction" eSuperTypes="#//Processes/Process.1"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalActivity" eSuperTypes="#//Processes/Process.1"/>
    <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Processes/Process.1"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProjectActivity" eSuperTypes="#//Processes/Process.1"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessGeneralization">
      <eStructuralFeatures xsi:type="ecore:EReference" name="specificProcess" lowerBound="1"
          upperBound="-1" eType="#//Processes/Process.1" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="generalProcess" lowerBound="1"
          upperBound="-1" eType="#//Processes/Process.1" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityPerformableUnderCondition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          upperBound="-1" eType="#//Processes/Process.1" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MapsToCapability">
      <eStructuralFeatures xsi:type="ecore:EReference" name="processmappedProcess"
          lowerBound="1" upperBound="-1" eType="#//Processes/Process.1" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="describedBy">
    <eClassifiers xsi:type="ecore:EClass" name="MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EEnum" name="InformationKind" serializable="false">
      <eLiterals name="Information"/>
      <eLiterals name="DomainInformation" value="1"/>
      <eLiterals name="PositionReferenceFrame" value="2"/>
      <eLiterals name="PedigreeInformation" value="3"/>
      <eLiterals name="Data" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Information" eSuperTypes="#//describedBy/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EDataType" name="NewDataType2" instanceTypeName="newDataType2"/>
    <eClassifiers xsi:type="ecore:EClass" name="UAFElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="information" upperBound="-1"
          eType="#//describedBy/Information" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//describedBy/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalConstraint" eSuperTypes="#//describedBy/Rule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceConstraint" eSuperTypes="#//describedBy/Rule"/>
    <eClassifiers xsi:type="ecore:EClass" name="SecurityConstraint" eSuperTypes="#//describedBy/Rule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ServicePolicy" eSuperTypes="#//describedBy/Rule"/>
  </eSubpackages>
  <eSubpackages name="Traceability">
    <eClassifiers xsi:type="ecore:EClass" name="MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Implements" eSuperTypes="#//Traceability/MeasurableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalAgent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizedOperationalPerformer"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourcePerformer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizingResource" lowerBound="1"
          upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalExchange">
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizedOperationalExchange"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceExchange">
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizingResourceInteractions"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActualEnduringTask">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mplementedEnduringTask"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementedOperationalConnector"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementingResourceConnector"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizedResourceConnector"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceInterface">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mplementedServiceInterface"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceInterface">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementingResourceInterface"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalActivity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizedActivity" lowerBound="1"
          upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementingActivity"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="erviceFunction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizedServiceFunction"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Function">
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizingFunction" lowerBound="1"
          upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementingDataElement"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InformationElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mplementedInformationElement"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalRole">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementedOperationalRole"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceRole">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementingResourceRole"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalInterface">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementedOperationalInterface"
          lowerBound="1" upperBound="-1" eType="#//Traceability/Implements" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
