<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Resources">
  <eClassifiers xsi:type="ecore:EClass" name="resource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="type_one" eSuperTypes="#//resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="type_two" eSuperTypes="#//resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="type_three" eSuperTypes="#//resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="type_four" eSuperTypes="#//resource"/>
</ecore:EPackage>
